spring.application.name=interviewai
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_ai
spring.datasource.username=postgres
spring.datasource.password=siri3288S@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true